### ISSUE TITLE
Rename project to leanix-admin-cli

### ISSUE THREAD

**Issue by andrechrist** [zalando-incubator/leanix-admin-cli#6]
As said before, we really like this project as it makes life so much easier with backup and restore. As we are having an internal project called leanix-admin, it tends to be a bit confusing in naming. Therefore I suggest to rename to leanix-admin-cli if that is possible within the incubator.

**Comment by harti2006** [comment]
No problem, we can easily do this.

**Comment by harti2006** [comment]
Done
