### ISSUE TITLE
Ordering of Fact Sheet types

### ISSUE THREAD

**Issue by romansaul** [zalando-incubator/leanix-admin-cli#8]
We observed that the tool may change the order of Fact Sheet types in the datamodel. The order in the datamodel defines the order of the types in our UI (type facet, create new dialog).

First guess: Python’s json.load or json.dump use an unordered dictionary

LeanIX will think about changing the json type of factSheets from object to array:
```
{
  "factSheets": [
    {
      "type": "Application",
      "config": {},
      "fields": []
    },
    {
      "type": "OrgUnit",
      "config": {},
      "fields": []
    }
  ]
}
```
Another solution would be to completely ignore the ordering in the data model and instead define a field "order" for each Fact Sheet type in the view model.

I created a corresponding ticket in LeanIX's internal bug tracker:  https://www.pivotaltracker.com/story/show/144032993

**Comment by andrechrist** [comment]
@harti2006 Please see my latest pull request. The problem is gone when we use Python > 3.6. We have therefore added a docker container around the command
